spring:
  profiles:
    active: dev
  port: 8001
  # set vault
  config:
    import: optional:vault://
  cloud:
    vault:
      enabled: true
      url: http://tracking.mncf.io:8200
      scheme: http
      token: hvs.CAESIN5SlnxfDuDy9Kp4PHa1aCG9z995GCqcmiO6gFoT1sVkGh4KHGh2cy4xYWppanZGdUlsTndreGlZbzdQQVg1d2o
      port: 8200
      connection-timeout: 5000
      read-timeout: 15000
      kv:
        enabled: true
        backend: kv
        application-name: "${spring.profiles.active}"
#        default-context: kv
#        profile-separator: /
#        profiles: dev
  web:
    resources:
      # 404 Exception 을 Custom 하기 위한 설정
      add-mappings: false
  mvc:
    # 404 Exception 을 Custom 하기 위한 설정
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tracking.mncf.io:3306?serverTimezone=UTC&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: auth
    password: coffee!@2023
#    password: ${password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  error:
    whitelabel:
      # spring boot 가 제공하는 기본 예외페이지 제거
      enabled: false

logging:
  level:
    root: info
    org.springframework: info
    com.morning.auth: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method
    # Schema Tab 제거
    default-models-expand-depth: -1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# mybatis
mybatis:
  configuration:
    cache-enabled: false  # 캐시 전역 사용여부
    jdbc-type-for-null: 'null'  # jdbc 타입이 없을때 null로 반환
    use-generated-keys: true # 생성키에대한 jdbc 지원 허용
    default-executor-type: reuse # 디폴트 실행자 설정
    map-underscore-to-camel-case: true  # camelcase로 자동 변환
    arg-name-based-constructor-auto-mapping: true # 생성자 만들때 자동 매핑
    nullable-on-for-each: false # 'null'이면 Null로 인식

# password rule
password:
  valid:
    min-pattern: .{10,}
    max-pattern: .{1,32}
    number-pattern: .*\d+.*
    special-pattern: .*[!@#$%^&*()_+{}\[\]:;<>,.?/~`].*
    character-pattern: .*[a-zA-Z].*

# crypto
crypto:
  password: 가나다라
  byte-array: 16
  secret-key-algorithm: AES
  transformation: AES/CBC/PKCS5Padding
  digest-algorithm: SHA-256
