name: Docker Image CI and Trigger Remote Docker Compose

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build Spring Boot App
      run: |
        ./gradlew build

    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/auth_api .
        docker push ${{ secrets.DOCKER_USERNAME }}/auth_api

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: 'ubuntu'
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: '22'
        script: |
          cd mncf.tracking.infra/dev
          docker stop auth_api_container
          docker rm auth_api_container
          docker rmi ${{ secrets.DOCKER_USERNAME }}/auth_api:latest
          docker-compose up --build -d
